### ISSUE TITLE
How can I trap the `rejected` errors

### ISSUE THREAD

**Issue by binarykitchen** [andris9/nodemailer-smtp-transport#22]
When I am on localhost and send to an invalid local email address, i.E. `idonotexist@localhost`, then I get that error

```
    Can't send mail - all recipients were rejected
    
    Error: Can't send mail - all recipients were rejected
        at SMTPConnection._formatError (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:388:15)
        at SMTPConnection._actionRCPT (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:911:34)
        at SMTPConnection.<anonymous> (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:885:18)
        at SMTPConnection._processResponse (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:511:16)
        at SMTPConnection._onData (/home/michael-heuberger/binarykitchen/code/videomail.io/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:357:10)
        at emitOne (events.js:77:13)
        at TLSSocket.emit (events.js:169:7)
        at readableAddChunk (_stream_readable.js:146:16)
        at TLSSocket.Readable.push (_stream_readable.js:110:10)
        at TLSWrap.onread (net.js:521:20)
```

How can I trap these error events?

**Comment by andris9** [comment]
Check the error and info arguments for `sendMail` callback. If all recipients were rejected, then sending is considered as failed and you get the errors from the `error` argument. If at least one recipient was accepted, then the message is sent and you can find the errors for rejected addresses from the `info` argument.

**Comment by binarykitchen** [comment]
great, very valuable information - thanks
