### ISSUE TITLE
Missing 'getToken' method from this._auth.xoauth2 object

### ISSUE THREAD

**Issue by ggallo** [andris9/nodemailer-smtp-transport#23]
Using nodemailer-smtp-transport@1.0.3 via nodemailer@1.5.0 (i.e. this might belong [here](https://github.com/andris9/Nodemailer/issues))

Setting up the mailer:
```
var transporter = nodemailer.createTransport({
        service: 'Gmail',
        auth: {
          xoauth2: {
            user: "XXXXXXXX@gmail.com",
            clientId: "XXXXXXX.apps.googleusercontent.com",
            clientSercret: "XXXXXXXXXX",
            refreshToken: "XXXXXXXX"
          }
        }
    });
```

And the resulting error:
```
TypeError: Object #<Object> has no method 'getToken'
    at SMTPConnection._handleXOauth2Token (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:961:67)
    at SMTPConnection.login (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:233:18)
    at SMTPTransport.<anonymous> (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:96:24)
    at SMTPConnection.g (events.js:180:16)
    at SMTPConnection.emit (events.js:92:17)
    at SMTPConnection._actionEHLO (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:692:10)
    at SMTPConnection._processResponse (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:511:16)
    at SMTPConnection._onData (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:357:10)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:442:13)
```
The initial offending code for convenience:
```
SMTPConnection.prototype._handleXOauth2Token = function(isRetry, callback) {
    this._currentAction = function(str) {
        this._actionAUTHComplete(str, isRetry, callback);
    }.bind(this);

    if (this._auth.xoauth2 && typeof this._auth.xoauth2 === 'object') {
        this._auth.xoauth2[isRetry ? 'generateToken' : 'getToken'](function(err, token) {
            if (err) {
                return callback(this._formatError(err, 'EAUTH'));
            }
            this._sendCommand('AUTH XOAUTH2 ' + token);
        }.bind(this));
    } else {
        this._sendCommand('AUTH XOAUTH2 ' + this._buildXOAuth2Token(this._auth.user, this._auth.xoauth2));
    }
};
```

**Comment by ggallo** [comment]
Aaaaand closing because this actually belongs [here](https://github.com/andris9/smtp-connection/issues). Sorry about that
